version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selfhosting-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - MONGODB_URL=${MONGODB_URL}
    depends_on:
      - mongodb
    networks:
      - default
      - npm_ha

  mongodb:
    image: mongo:5.0
    container_name: selfhosting-db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - default

volumes:
  mongodb_data:

networks:
  default:
  npm_ha:
    external: true
